# Site settings
title: 2D 벡터의 이해, 그리고 애니메이션
email: hansune@me.com
description:
  기초적인 2D 운동 벡터에 대해 배울 수 있습니다.
  벡터를 이해하면, 움직임을 만드는 데 큰 도움이 됩니다.

baseurl: "/2DVectors" # the subpath of your site, e.g. /blog/
url: "http://brownsoo.github.io" # the base hostname & protocol for your site
github_username:  brownsoo

safe: true
lsi: false
source: .
highlighter: rouge

# Build settings
markdown: kramdown
collections:
 tutorials:
  output: true
  permalink: /:path/

exclude: [
.git,
.gitignore,
.sass-cashe,
README.md
]

# serving
port: 4000
host: 127.0.0.1
