# Site settings
title: 2D 벡터의 이해, 그리고 애니메이션
email: hansune@me.com
description:
  기초적인 2D 운동 벡터에 대해 배울 수 있습니다.
  벡터를 이해하면, 움직임을 만드는 데 큰 도움이 됩니다.

baseurl: "/2DVectors" # the subpath of your site, e.g. /blog/
url: "http://brownsoo.github.io" # the base hostname & protocol for your site
github_username:  brownsoo

safe: true
lsi: false
source: .
highlighter: rouge

# Build settings
markdown: kramdown
collections:
 tutorials:
  output: true
  permalink: /:path/


# serving
port: 4000
host: 127.0.0.1


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/