# Site settings
title: Vectors for Animation
email: hansoo.lab@gmail.com
description:
  운동 벡터에 대한 기초를 배울 수 있습니다.
  벡터를 이해하면, 움직임을 만드는 데 큰 도움이 됩니다.

baseurl: "/vectors" # the subpath of your site, e.g. /blog/
url: "http://brownsoo.github.io" # the base hostname & protocol for your site
github_username:  brownsoo

safe: true
lsi: false
source: .
highlighter: pygments

# Build settings
markdown: kramdown
collections:
 tutorials:
  output: true
  permalink: /:path/

exclude: [
.git,
.gitignore,
README.md,
.sass-cashe
]

# serving
port: 4000
host: 127.0.0.1
